services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    volumes:
      - ./mssql_data:/var/opt/mssql
      - ./mssql_scripts:/home/mssql_scripts
